[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:${PORT} app:app"
healthcheckPath = "/callback"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
healthcheckProtocol = "http"
healthcheckInterval = 30
